### ISSUE TITLE
Global install clashes for the name "gobin"

### ISSUE THREAD

**Issue by myitcv** [myitcv/gobin#13]
With #10 it will be possible to:

```
$ gobin github.com/myitcv/gobin
```

However, it will also be possible to:

```
$ gobin github.com/someother/gobin
```

at which point `gobin` will have replaced itself with something that is not this `gobin`.

Options here:

* rename the project from `gobin` to something "definitely" unique
* have this `gobin` maintain a safe copy of itself at a unique name, e.g. `gobin-stashed` (suggestion per @mvdan), so that if that happens a user can bootstrap themselves out of the hole

**Comment by mvdan** [comment]
A third option would even be to error out, or to require a "yes I want to replace this very binary" flag.

I'm not sure on the unique binaries, because those could end up piling up, so you'd have to take care of that too. I'd imagine that if someone breaks `gobin` they'd notice at the next call, so one stashed binary should be enough for pretty much every scenario.

**Comment by myitcv** [comment]
I think we roughly decided (on Slack) that nothing needs to be done here (for now). Closing
