### ISSUE TITLE
-nonet broken?

### ISSUE THREAD

**Issue by quite** [myitcv/gobin#73]
-nonet does not seem work. Or am I possibly misunderstanding something?

```
$ rm -rf ~/.cache/gobin ~/go/bin/gohack
$ gobin github.com/rogpeppe/gohack@v1.0.0
Installed github.com/rogpeppe/gohack@v1.0.0 to /home/quite/go/bin/gohack
$ gobin -nonet github.com/rogpeppe/gohack
Installed github.com/rogpeppe/gohack@v1.0.1 to /home/quite/go/bin/gohack
```

**Comment by myitcv** [comment]
```
If the -nonet flag is provided, gobin will only check the module download cache. 
```

So in the second invocation the command succeeds because it's checking the module cache that was populated in either the previous command or before. The module cache exists in `$GOPATH/pkg/mod`. 

If you were to specify a version in the second call that does _not_ exist in the module cache then yes, it would fail. But you've not specified a version and so `gobin` will default to choosing the latest version if finds in the module download cache.

**Comment by quite** [comment]
I understand. I was actually trying to use `gobin -nonet -v` to see which version that is currently installed, in use. But that would currently never work, because the module cache may have other versions. Currently one would have to rely on the actual binary itself to be able to tell which version it is.

**Comment by myitcv** [comment]
Yes, you could rely on the program to tell you via `-v` or some such. Or you could use https://github.com/rsc/goversion:

```
> exec gobin github.com/rogpeppe/gohack
Installed github.com/rogpeppe/gohack@v1.0.1 to $WORK/gopath/bin/gohack
> exec gobin -run rsc.io/goversion -m $GOPATH/bin/gohack
$WORK/gopath/bin/gohack go1.12.1
        path  github.com/rogpeppe/gohack
        mod   github.com/rogpeppe/gohack       v1.0.1
        dep   github.com/rogpeppe/go-internal  v1.0.0
        dep   golang.org/x/tools               v0.0.0-20180917221912-90fa682c2a6e
        dep   gopkg.in/errgo.v2                v2.1.0
```

I'll close this issue for now but please shout if there's something that could be improved in terms of docs etc.
